import { IEvent } from "@/database";

export const MOCK_EVENTS: IEvent[] = [
  {
    _id: "1",
    title: "Next.js 16 Launch Event",
    slug: "nextjs-16-launch-event",
    description:
      "Join us for the official launch of Next.js 16 with exciting new features",
    overview:
      "Discover the latest features in Next.js 16 including improved performance and new APIs",
    image: "/images/event1.png",
    venue: "Tech Hub Convention Center",
    location: "San Francisco, CA",
    date: "2025-12-15",
    time: "10:00 AM",
    mode: "Hybrid",
    audience: "Developers",
    agenda: ["Keynote", "Feature Demo", "Q&A Session"],
    organizer: "Vercel",
    tags: ["Next.js", "React", "Web Development"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
  {
    _id: "2",
    title: "React Summit 2025",
    slug: "react-summit-2025",
    description: "The biggest React conference of the year",
    overview: "Learn from React core team members and industry experts",
    image: "/images/event2.png",
    venue: "Grand Conference Hall",
    location: "New York, NY",
    date: "2025-11-20",
    time: "9:00 AM",
    mode: "In-person",
    audience: "Frontend Developers",
    agenda: ["Opening Keynote", "Technical Sessions", "Networking"],
    organizer: "React Community",
    tags: ["React", "JavaScript", "Frontend"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
  {
    _id: "3",
    title: "TypeScript Workshop",
    slug: "typescript-workshop",
    description:
      "Hands-on TypeScript workshop for beginners and intermediate developers",
    overview: "Master TypeScript fundamentals and advanced patterns",
    image: "/images/event3.png",
    venue: "Online",
    location: "Virtual",
    date: "2025-11-25",
    time: "2:00 PM",
    mode: "Online",
    audience: "All Levels",
    agenda: ["TypeScript Basics", "Advanced Types", "Real-world Projects"],
    organizer: "TypeScript Academy",
    tags: ["TypeScript", "JavaScript", "Programming"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
  {
    _id: "4",
    title: "Web Development Bootcamp",
    slug: "web-development-bootcamp",
    description:
      "Intensive bootcamp covering modern web development technologies",
    overview:
      "Learn HTML, CSS, JavaScript, and modern frameworks in this comprehensive bootcamp",
    image: "/images/event4.png",
    venue: "Code Academy",
    location: "Austin, TX",
    date: "2025-12-01",
    time: "9:00 AM",
    mode: "In-person",
    audience: "Beginners",
    agenda: [
      "HTML & CSS Fundamentals",
      "JavaScript Essentials",
      "Framework Introduction",
    ],
    organizer: "Code Academy",
    tags: ["Web Development", "JavaScript", "HTML", "CSS"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
  {
    _id: "5",
    title: "AI & Machine Learning Conference",
    slug: "ai-machine-learning-conference",
    description: "Explore the latest trends in AI and machine learning",
    overview:
      "Join industry leaders discussing cutting-edge AI technologies and applications",
    image: "/images/event5.png",
    venue: "Innovation Center",
    location: "Seattle, WA",
    date: "2025-12-10",
    time: "8:00 AM",
    mode: "Hybrid",
    audience: "Data Scientists",
    agenda: ["AI Trends", "ML Applications", "Panel Discussion"],
    organizer: "AI Institute",
    tags: ["AI", "Machine Learning", "Data Science"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
  {
    _id: "6",
    title: "DevOps Best Practices",
    slug: "devops-best-practices",
    description: "Learn DevOps best practices from industry experts",
    overview:
      "Master CI/CD, containerization, and cloud infrastructure management",
    image: "/images/event6.png",
    venue: "Cloud Center",
    location: "Boston, MA",
    date: "2025-12-20",
    time: "1:00 PM",
    mode: "Online",
    audience: "DevOps Engineers",
    agenda: ["CI/CD Pipelines", "Docker & Kubernetes", "Cloud Infrastructure"],
    organizer: "DevOps Community",
    tags: ["DevOps", "CI/CD", "Docker", "Kubernetes"],
    createdAt: new Date(),
    updatedAt: new Date(),
  } as IEvent,
];
